### ISSUE TITLE
Showing the progress of solving

### ISSUE THREAD

**Issue by quangdutran** [artuncolak/Sudoku-Solver#1]
Hi Artun,

Much impressed by the work you've done with the solver. Could you please share the idea and explaination if possible for the part of showing the progress of the solving? 

I am trying to understand the part where you using async await promise to show how the actual backtracking implemented behind the scene but I am stuck. 

Really appreciate if you could share your idea. Thank you!

**Comment by artuncolak** [comment]
Hi Quang,
Thank you for your interest with the solver. I actually pushed all the steps to an array while solving recursively then set all the steps individually to a state. Before each setState function i created a timeout promise which is waiting 5ms.

[solveRecursive](https://github.com/artuncolak/Sudoku-Solver/blob/6ac9b0e57d45fa464f01ce93b4b774dd5f433369/src/sudokuService.js#L75-L97)

[showProgress](https://github.com/artuncolak/Sudoku-Solver/blob/6ac9b0e57d45fa464f01ce93b4b774dd5f433369/src/components/SudokuSolver.jsx#L33-L41)

**Comment by quangdutran** [comment]
Oh thank you for sharing. That's why when user does not want to see the progress, the last item of the array is taken and show on board. I think there are a lot of values in this array, 9^n items where n is the number of empty cell that we need to fill in (correct me if I am wrong).

Did you do something to optimize this part?

**Comment by artuncolak** [comment]
Excatly, Yes there are a lot of values. it is not the best solution. I couldn't solve how to handle async await in a recursive function back then. Maybe i will take a look again.

**Comment by quangdutran** [comment]
I have the same struggle so I look up online and see your solution. The super big array approach still works though. The nature of javascript make this sound-simple task so hard.

Hope you could share with me if you come up with something. I would too. Cheers Artun!

**Comment by artuncolak** [comment]
If i come up with something sure i will share.  Cheers!
